<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.53">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Generational Differences in Student Loan Debt and Implications on Homeownership Trends</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="capstone_files/libs/clipboard/clipboard.min.js"></script>
<script src="capstone_files/libs/quarto-html/quarto.js"></script>
<script src="capstone_files/libs/quarto-html/popper.min.js"></script>
<script src="capstone_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="capstone_files/libs/quarto-html/anchor.min.js"></script>
<link href="capstone_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="capstone_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="capstone_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="capstone_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="capstone_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="capstone_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="capstone_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="capstone_files/libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="capstone_files/libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="capstone_files/libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Generational Differences in Student Loan Debt and Implications on Homeownership Trends</h1>
            <p class="subtitle lead">MSDS Capstone 2024</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Authors</div>
      <div class="quarto-title-meta-contents">
               <p>Leann Kim </p>
               <p>Kassandra Traieh </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition">Data Acquisition</a></li>
  <li><a href="#data-cleaning-feature-engineering" id="toc-data-cleaning-feature-engineering" class="nav-link" data-scroll-target="#data-cleaning-feature-engineering">Data Cleaning &amp; Feature Engineering</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#materials-list-software-used" id="toc-materials-list-software-used" class="nav-link" data-scroll-target="#materials-list-software-used">1. Materials List (Software used)</a></li>
  <li><a href="#data-exploration-and-initial-analysis" id="toc-data-exploration-and-initial-analysis" class="nav-link" data-scroll-target="#data-exploration-and-initial-analysis">2. Data Exploration and Initial Analysis</a></li>
  <li><a href="#identification-of-significant-features" id="toc-identification-of-significant-features" class="nav-link" data-scroll-target="#identification-of-significant-features">3. Identification of Significant Features</a></li>
  <li><a href="#building-a-linear-regression-model" id="toc-building-a-linear-regression-model" class="nav-link" data-scroll-target="#building-a-linear-regression-model">4. Building a Linear Regression Model</a></li>
  <li><a href="#building-a-random-forest-model" id="toc-building-a-random-forest-model" class="nav-link" data-scroll-target="#building-a-random-forest-model">5. Building a Random Forest Model</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#trends-over-time" id="toc-trends-over-time" class="nav-link" data-scroll-target="#trends-over-time">Trends Over Time</a></li>
  <li><a href="#linear-regression-model" id="toc-linear-regression-model" class="nav-link" data-scroll-target="#linear-regression-model">Linear Regression Model</a>
  <ul class="collapse">
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit">Model Fit</a></li>
  </ul></li>
  <li><a href="#random-forest-model" id="toc-random-forest-model" class="nav-link" data-scroll-target="#random-forest-model">Random Forest Model</a>
  <ul class="collapse">
  <li><a href="#model-fit-1" id="toc-model-fit-1" class="nav-link" data-scroll-target="#model-fit-1">Model Fit</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As current students, student loans are at the forefront of our minds, looming over us as we juggle the stress of financial burdens and the need for education to grow and succeed in life. Societal pressures push us to graduate college, start our careers, buy a house, and start a family. But are Millennials and Gen Z-ers able to fall into place and follow in the footsteps of the generations before them? Or are they facing additional challenges with the outstanding debt they’re accumulating from student loans? This project aims to shed light on how differences in student loan debt between older and current generations influence homeownership trends.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Historically, homeownership has been a cornerstone of wealth accumulation for American families, providing stability and financial security across generations <span class="citation" data-cites="homeownership2024">(<a href="#ref-homeownership2024" role="doc-biblioref">Association, 2024</a>)</span>. However, in the aftermath of the Great Recession and amidst rising costs of higher education, younger generations are increasingly burdened by substantial student loan debt <span class="citation" data-cites="NIH CFR equitablegrowth">(<a href="#ref-CFR" role="doc-biblioref">Editors, 2024</a>; <a href="#ref-equitablegrowth" role="doc-biblioref">Kopparam &amp; Clemens, 2020</a>; <a href="#ref-NIH" role="doc-biblioref">Martin &amp; E., 2021</a>)</span>. According to 2024 data, outstanding student loan debt in the United States has surpassed $1.75 trillion, which is a 67% increase from the previous decade <span class="citation" data-cites="federal2024">(<a href="#ref-federal2024" role="doc-biblioref">Governors of the Federal Reserve System, 2020</a>)</span>. Research has shown that high levels of student debt can delay or reduce the likelihood of homeownership <span class="citation" data-cites="ChicagoJournal FederalReserveBoston Upjohn">(<a href="#ref-FederalReserveBoston" role="doc-biblioref">Cooper &amp; Wang, 2014</a>; <a href="#ref-Upjohn" role="doc-biblioref">Gicheva &amp; Thompson, 2015</a>; <a href="#ref-ChicagoJournal" role="doc-biblioref">Mezza et al., 2020</a>)</span>. By comparing older generations (Baby Boomers and Gen X) with younger generations (Millennials), we can better understand how the landscape of student debt has evolved and its implications for long-term financial decisions such as homeownership.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Understanding the differences in student loan debt composition across generations holds personal significance for us as members of the current generations facing the burden of student loans. It speaks to the experiences of students navigating the complexities of higher education financing and the challenges they face in achieving future financial stability, including homeownership. By examining these dynamics, our research aims to empower individuals with knowledge to make informed financial decisions and advocate for systemic reforms.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This study also reflects on the evolving societal norms and expectations surrounding higher education and homeownership. It highlights the shift towards higher education attendance and the resulting increase in student loan debt, which affects traditional milestones such as homeownership. Ultimately, our research contributes to building a more inclusive and resilient society by addressing systemic barriers to economic opportunity and wealth accumulation.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In summary, our research holds significant merit, with the potential to drive positive societal change. A better understanding of generational differences in student loan debt and its implications for homeownership rates can lead to more informed policies, such as targeted student loan forgiveness programs or tailored financial assistance for first-time homebuyers burdened by educational debt. It can also enhance educational programs by promoting financial literacy initiatives that help students make informed borrowing decisions. Furthermore, this understanding can contribute to a more equitable and prosperous future by addressing disparities in debt accumulation across generations and fostering greater economic mobility for younger individuals.</p>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<section id="data-acquisition" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition">Data Acquisition</h2>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The acquisition of student loan data and homeownership data proved challenging due to several factors. A significant lack of publicly available data, especially on student loans dating back to 1990, was compounded by the unavailability of the necessary raw data on government portals and academic repositories. The data we encountered was predominantly aggregated by age group, with limited access to detailed, disaggregated datasets that would allow for more granular analysis. Furthermore, many of the existing studies that addressed related topics did not provide explicit citations or source details for their data, making it difficult to trace the origins and verify the reliability of the information used in previous research. This lack of transparency and accessibility posed significant obstacles to obtaining the comprehensive and historical data required for our study.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To perform our analysis, we utilized data from the Federal Reserve and Census surveys within the 1989-2022 time frame. The Federal Reserve survey <span class="citation" data-cites="federal2024">(<a href="#ref-federal2024" role="doc-biblioref">Governors of the Federal Reserve System, 2020</a>)</span> consisted of age groups, the percentage of those who had a mortgage, and the percentage of those with education loans, and was stored in various tabs in an Excel spreadsheet. The Census survey <span class="citation" data-cites="Census2019">(<a href="#ref-Census2019" role="doc-biblioref">Bureau, 2024</a>)</span>, also stored in various tabs in an Excel spreadsheet, included age groups, the total number of people who were surveyed, and the number of homeowners within each age group. To further explore our research question and to supplement our existing tables, we found data on the amount of debt students had at the time of their graduation <span class="citation" data-cites="Studentdebt2023">(<a href="#ref-Studentdebt2023" role="doc-biblioref">McLoughlin, 2023</a>)</span>. This table included graduation year, amount of debt at graduation, average starting salary out of college, and the debt-to-income ratio. The original data structure can be seen in <a href="#figure-1">Figure 1</a> with an explanation of the features in the Data Dictionary below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/erd1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure 1: Entity-Relationship Diagram showing original features extracted from survey and student debt datasets"><img src="images/erd1.png" class="img-fluid figure-img" width="400" alt="Figure 1: Entity-Relationship Diagram showing original features extracted from survey and student debt datasets"></a></p>
<figcaption>Figure 1: Entity-Relationship Diagram showing original features extracted from survey and student debt datasets</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Original Data Dictionary - Features, Descriptions, and Sources (Click to Expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="table">
<caption>Table 1: Survey of Consumer Finances 1989-2022: a normally triennial cross-sectional survey of U.S. families showcasing family holdings of debt by selected characteristics of families and type of debt.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 82%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>year</code></td>
<td>Survey year from 1989-2022 in ncrements of 3 years</td>
</tr>
<tr class="even">
<td><code>age_group</code></td>
<td>Age groups: 18-34, 35-44, 45-54, 55-64, 65-74, 75+</td>
</tr>
<tr class="odd">
<td><code>percent_mortgage</code></td>
<td>Percent of mortgage debt an individual within the age group holds on average</td>
</tr>
<tr class="even">
<td><code>percent_education_loan</code></td>
<td>Percent of education loan debt an individual within the age groups holds on average</td>
</tr>
</tbody>
</table>
<p><br><br></p>
<table class="table">
<caption>Table 2: Census Housing Vacancy Survey: historical data on rental and homeowner vacancy rates in the U.S.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>year</code></td>
<td>Survey year from 1989-2022 in increments of 3 years</td>
</tr>
<tr class="even">
<td><code>age_group</code></td>
<td>Age groups: 18-24, 25-29, 30-34, 35-39, 40-44, 45-49, 50-54, 55-59, 60-64, 65-69, 70-74, 75+</td>
</tr>
<tr class="odd">
<td><code>total_surveyed</code></td>
<td>Total number of homes surveyed</td>
</tr>
<tr class="even">
<td><code>total_owner</code></td>
<td>Total number of homes surveyed that were owned</td>
</tr>
</tbody>
</table>
<p><br><br></p>
<table class="table">
<caption>Table 3: Student Loan Debt by Year: average debt by year of graduation for students who graduated with a bachelor’s degree</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>grad_year</code></td>
<td>Graduation year from 1970-2021 in varying increments</td>
</tr>
<tr class="even">
<td><code>debt_at_grad</code></td>
<td>Average student loan debt at graduation</td>
</tr>
<tr class="odd">
<td><code>avg_start_salary</code></td>
<td>Average starting salary after graduation</td>
</tr>
<tr class="even">
<td><code>avg_debt_to_income</code></td>
<td>Average debt to average income percentage</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="data-cleaning-feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-feature-engineering">Data Cleaning &amp; Feature Engineering</h2>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The data preparation process involved extensive cleaning and feature engineering in Excel and PostgreSQL. It is crucial to emphasize that all data was aggregated, ensuring that no personally identifying information was included within the datasets. For the Federal Reserve data, we extracted variables such as the survey year, age groups, the percentage of families in those age groups with a mortgage loan, and the percentage of families in that age group with an education loan. Similarly, for the Census data, we extracted the survey year, age groups, the total number of homes surveyed, and the total number of homes that were owned. All these variables were organized in a structured manner to facilitate analysis. It is important to note that the age groups from the Federal Reserve and Census data exhibited overlap, although they were categorized differently. The Federal Reserve data utilized broader age categories, while the Census data employed more granular age bins. Specifically, the Federal Reserve age groups were: less than 35, 35-44, 45-54, 55-64, 65-74, and 75+. In contrast, the Census data age groups were segmented as follows: less than 25, 25-29, 30-34, 35-39, …, 70-74, and 75+.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Once we created these two tables in PostgreSQL, we split each table’s age groups into a minimum age and a maximum age for ease of joining the two tables together. Once we created those new columns in both the Federal Reserve and Census tables, we joined our data on survey year, minimum age, and maximum age, which we treated as primary composite keys. This join is visualized in <a href="#figure-2">Figure 2</a>. In the join, we ensured that the broader Federal Reserve age ranges were matched with the more granular Census age ranges. Although the join conditions account for overlapping age ranges, it is important to note that this can lead to the duplication of data. Specifically, when a Federal Reserve age range spans multiple Census age ranges, the same Federal Reserve data might be repeated across multiple rows in the joined table. This duplication can impact subsequent analyses if not properly accounted for, as it might inflate counts or skew averages, making it crucial to carefully consider how the joined data is used in downstream processes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/age_group%20(2).png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure 2: Process flow diagram: Splitting age groups and joining on year, min_age, and max_age"><img src="images/age_group%20(2).png" class="img-fluid figure-img" width="450" alt="Figure 2: Process flow diagram: Splitting age groups and joining on year, min_age, and max_age"></a></p>
<figcaption>Figure 2: Process flow diagram: Splitting age groups and joining on year, min_age, and max_age</figcaption>
</figure>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Upon joining these two tables, we proceeded to assign generation names for each age range. This involved calculating the minimum and maximum birth years using the survey year along with the minimum and maximum ages. To classify each row into a generational cohort (Traditionalist, Baby Boomer, Generation X, Millennial, or Gen Z), we created a formula to manage overlaps by comparing the minimum and maximum birth years to determine the closest generational boundary alignment for each row. To help visualize this process, please see <a href="#figure-3">Figure 3</a>. We also created new columns for minimum and maximum graduation years. This was done by assuming the average college graduation age to be 21 and adding this to the minimum and maximum birth years. It’s important to note that using a single average age may lead to inaccuracies in calculating the minimum and maximum graduation years, which could affect subsequent analyses and the classification of individuals into generational cohorts.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/age_group%20(4).png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure 3: Creating min_birth and max_birth year and assigning each row a generation using generation birth year ranges [@generations]"><img src="images/age_group%20(4).png" class="img-fluid figure-img" width="450" alt="Figure 3: Creating min_birth and max_birth year and assigning each row a generation using generation birth year ranges (Bialik &amp; Fry, 2019)"></a></p>
<figcaption>Figure 3: Creating min_birth and max_birth year and assigning each row a generation using generation birth year ranges <span class="citation" data-cites="generations">(<a href="#ref-generations" role="doc-biblioref">Bialik &amp; Fry, 2019</a>)</span></figcaption>
</figure>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Finally, we integrated our student debt dataset, which included variables such as debt at graduation, average starting salary, and debt-to-income percentage by graduation year. The data source did not provide a downloadable file. Consequently, the values were manually entered into Excel and subsequently imported into PostgreSQL for analysis. We aligned each row of our joined dataset to the corresponding debt figures by comparing the minimum and maximum graduation years to determine the closest match to the graduation year in our debt dataset. Although the assignments were done as carefully as possible, there is a chance that some inaccuracies may remain due to variations in actual graduation ages and the potential misalignment of graduation years within the dataset.</p>
<p>The below Data Dictionary detail the dataset and features.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Final Data Dictionary - Features and Descriptions (Click to Expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="table">
<caption>Table 4: Survey of Consumer Finances 1989-2022: a normally triennial cross-sectional survey of U.S. families showcasing family holdings of debt by selected characteristics of families and type of debt.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>year</code></td>
<td>year of survey, in increments of 3</td>
</tr>
<tr class="even">
<td><code>census_min_birth_year</code></td>
<td>minimum birth year calculated from <code>year</code> and <code>census_min_age</code></td>
</tr>
<tr class="odd">
<td><code>census_max_birth_year</code></td>
<td>maximum birth year calculated from <code>year</code> and <code>census_max_age</code></td>
</tr>
<tr class="even">
<td><code>census_generation_name</code></td>
<td>generation name derived from <code>census_min_birth_year</code> and <code>census_max_birth_year</code></td>
</tr>
<tr class="odd">
<td><code>census_min_grad_year</code></td>
<td>minimum graduation year derived from <code>census_min_birth_year</code> + 21 years</td>
</tr>
<tr class="even">
<td><code>census_max_grad_year</code></td>
<td>maximum graduation year derived from <code>census_max_birth_year</code> + 21 years</td>
</tr>
<tr class="odd">
<td><code>debt_at_grad</code></td>
<td>average debt at year of graduation</td>
</tr>
<tr class="even">
<td><code>avg_start_salary</code></td>
<td>average starting salary post graduation</td>
</tr>
<tr class="odd">
<td><code>avg_debt_to_income</code></td>
<td>average debt to income percentage</td>
</tr>
<tr class="even">
<td><code>census_min_age</code></td>
<td>minimum age derived from age group</td>
</tr>
<tr class="odd">
<td><code>census_max_age</code></td>
<td>maximum age derived from age group</td>
</tr>
<tr class="even">
<td><code>total_surveyed</code></td>
<td>total number of those surveyed</td>
</tr>
<tr class="odd">
<td><code>total_owner</code></td>
<td>total number of those surveyed who own a home</td>
</tr>
<tr class="even">
<td><code>federal_min_age</code></td>
<td>minimum age derived from age group</td>
</tr>
<tr class="odd">
<td><code>federal_max_age</code></td>
<td>maximum age derived from age group</td>
</tr>
<tr class="even">
<td><code>percent_mortgage</code></td>
<td>percentage of those surveyed with mortgages</td>
</tr>
<tr class="odd">
<td><code>percent_education_loan</code></td>
<td>percentage of those surveyed with education loans</td>
</tr>
<tr class="even">
<td><code>generation_order</code></td>
<td>generations encoded (Baby Boomer = 1, Generation X = 2, Millennial = 3)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As mentioned previously, all the data from the Federal Reserve and Census surveys were anonymized to protect individual privacy, preventing the identification of specific individuals. Additionally, the data was presented in aggregated forms such as percentages and averages, rather than detailed individual records, to further safeguard privacy. However, despite these measures, the potential for bias remains a concern, as survey respondents may not fully represent the entire population, with certain demographics potentially being underrepresented. This is especially the case for our student loan debt dataset, where the sample population is unknown. Additionally, working with aggregated data can weaken the statistical power of analyses and increase the likelihood of Type II errors (failing to detect a true effect) or result in misleading statistics. Furthermore, although the Federal Reserve and Census data were obtained from reputable institutions, we were unable to verify the source of the student debt data. Consequently, we must depend on this analyst as a credible source for student debt information. We acknowledge the limitations of this dataset but feel that its inclusion was crucial for providing a more comprehensive analysis. We advise readers to consider the findings from this source alongside the more robust datasets and to be mindful of the potential impact on our study’s overall conclusions.</p>
</section>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In our dataset, there were relatively few features to choose from that could be associated with homeownership and student debt. Initially, we selected specific features and employed linear regression models to evaluate the influence of each feature on homeownership rates. To explore more intricate, non-linear relationships among the features, we then applied a Random Forest machine learning model. This approach allowed us to build upon the findings from our linear regression analysis and assess the relative importance of each feature. These methodologies together provide a comprehensive framework for understanding the potential impact of student loan debt and generational factors on homeownership rates.</p>
<section id="materials-list-software-used" class="level3">
<h3 class="anchored" data-anchor-id="materials-list-software-used">1. Materials List (Software used)</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The following section details the software and libraries utilized in our analysis. The tools listed were instrumental in processing data, performing statistical analyses, and generating visualizations. The specific software and versions used are as follows:</p>
<table class="table-striped table-hover table">
<caption>Table 5: Purpose of software and libraries used</caption>
<colgroup>
<col style="width: 23%">
<col style="width: 15%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Software/Library</th>
<th>Version</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Python</td>
<td>3.11.5</td>
<td>Used for scripting and data analysis</td>
</tr>
<tr class="even">
<td>Pandas</td>
<td>2.0.3</td>
<td>Data manipulation and analysis, particularly for handling structured data</td>
</tr>
<tr class="odd">
<td>NumPy</td>
<td>1.24.3</td>
<td>Numerical computing, used for array operations and mathematical functions</td>
</tr>
<tr class="even">
<td>Statsmodel</td>
<td>0.14.0</td>
<td>Implementation of statistical models, specifically used for ordinary least squares (linear regression) model</td>
</tr>
<tr class="odd">
<td>Skikit-learn</td>
<td>1.3.0</td>
<td>Machine learning library, used for implementing a random forest model</td>
</tr>
<tr class="even">
<td>SciPy</td>
<td>1.11.1</td>
<td>Used for statistical analysis and scientific computing</td>
</tr>
<tr class="odd">
<td>Matplotlib</td>
<td>3.7.2</td>
<td>Visualization library, used to create static visualizations</td>
</tr>
<tr class="even">
<td>Seaborn</td>
<td>0.12.2</td>
<td>Visualization library built on Matplotlib, used for creating attractive and informative statistical graphics</td>
</tr>
<tr class="odd">
<td>RStudio</td>
<td>2023.06.2+561</td>
<td>Used for creating additional visualizations outside of the Python environment</td>
</tr>
<tr class="even">
<td>ggplot2</td>
<td>3.4.0</td>
<td>Visualization library in R, used for creating complex and multi-layered plots</td>
</tr>
</tbody>
</table>
</section>
<section id="data-exploration-and-initial-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-and-initial-analysis">2. Data Exploration and Initial Analysis</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Initially, our dataset comprised 144 rows, covering Traditionalist, Baby Boomer, Generation X, Millennial, and Gen Z data. Initially, we intended to incorporate trends for Generation Z into our analysis. However, upon integrating all our datasets, we discovered that the available data for Generation Z was insufficient for a robust analysis of their student debt and homeownership rates. Including Generation Z data would have risked distorting the analysis of Baby Boomers, Generation X, and Millennials. Consequently, we decided to exclude Generation Z data from our analysis.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Additionally, while our survey datasets from the Census and Federal Reserve included detailed trends for Traditionalists, our student debt dataset only covered graduation years from 1970 onward. Since Traditionalists were born in 1945 or earlier and we assumed an average college graduation age of 21, they were not included in the student debt data. Given that the available dataset did not capture their college graduation years, we had to exclude Traditionalists from our analysis.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Following preliminary data cleaning and the focus on the Baby Boomer, Millennial, and Gen X cohorts, the dataset was refined to 92 rows, which were subsequently used for analysis. This reduction was essential to ensure the relevance and accuracy of the data in examining the targeted generational groups. While analyzing a small dataset can be manageable and insightful, it also comes with significant limitations related to statistical power, model complexity, and generalizability.</p>
<section id="analyzing-trends-over-time" class="level4">
<h4 class="anchored" data-anchor-id="analyzing-trends-over-time">Analyzing Trends Over Time</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Initially, we concentrated on examining the overall trend of student loan debt at graduation across different generations, specifically Baby Boomers, Generation X, and Millennials. To facilitate this analysis, we calculated the average graduation year for each entry in our dataset, covering graduates as far back as 1967. Additionally, we assessed the general trend in homeownership rates over the years. However, since our homeownership data only dates back to 1989, it presents a challenge in directly comparing the homeownership rates of Baby Boomers with our graduation debt trend.</p>
</section>
</section>
<section id="identification-of-significant-features" class="level3">
<h3 class="anchored" data-anchor-id="identification-of-significant-features">3. Identification of Significant Features</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As mentioned earlier, there were only a handful of features that we could employ in our analysis. In order to determine whether student debt affected homeownership trends, we created a variable to hold the homeownership rate, using the following formula:</p>
<div data-text-align="center">
<span class="math display">\[ \frac{to}{ts} * 100 = hr \]</span>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In this context, <i>to</i> represents the total number of survey respondents who own a home, corresponding to our total_owner variable. This is divided by <i>ts</i>, which represents the total number of households surveyed, corresponding to our total_surveyed variable. The resulting variable, <i>hr</i>, calculates the proportion of surveyed households that are owner-occupied. This variable was essential for analyzing the correlation between student debt levels and homeownership rates, offering insights into the potential impact of financial burdens on the likelihood of homeownership.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In our linear regression and random forest models, the dependent variable was <code>homeownership_rate</code>, while the independent variables included <code>debt_at_grad</code>, <code>avg_debt_to_income</code>, <code>avg_start_salary</code>, <code>percent_mortgage</code>, <code>percent_education_loan</code>, and <code>generation_order</code>.</p>
</section>
<section id="building-a-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="building-a-linear-regression-model">4. Building a Linear Regression Model</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To examine the relationship between homeownership rates and average debt at graduation across generations, we utilized a linear regression model. While our primary focus is to shed light on the impact of student loan debt by generation on homeownership rates, we included additional features, mentioned above, in our model to enhance its robustness and accuracy. We then created training and testing datasets with a 70%/30% split and utilized the statsmodel library to perform Ordinary Least Squares (OLS) regression to evaluate the performance of the model.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For the results of a linear regression analysis to be valid, certain assumptions about the data must be met. These assumptions include linearity, independence, homoscedasticity, normality, and lack of multicollinearity. We investigate each in the following sections.</p>
<section id="a.-testing-for-linearity" class="level4">
<h4 class="anchored" data-anchor-id="a.-testing-for-linearity">4a. Testing for Linearity</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The linearity assumption requires that the relationship between the independent variables and the dependent variable is linear. To assess this, we plotted the residuals (errors) against the predicted values to check for any patterns. By plotting residuals versus fitted values (or predictors), we checked for any systematic patterns. If the residuals display a clear pattern or trend, it suggests that the linear relationship assumption might be violated. Ideally, residuals should scatter randomly around zero, indicating that the linear model is appropriate.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The residuals vs.&nbsp;fitted values plot in <a href="#figure-4">Figure 4</a> shows a generally random scatter, but there is a very slight parabolic tendency present. Despite this minor curvature, the pattern is not strong enough to warrant a departure from a linear regression model.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/residuals1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure 4: Linearity Assumption Satisfied: Residuals vs.&nbsp;Fitted Plot shows no strong curvature of patterns"><img src="images/residuals1.png" class="img-fluid figure-img" alt="Figure 4: Linearity Assumption Satisfied: Residuals vs.&nbsp;Fitted Plot shows no strong curvature of patterns"></a></p>
<figcaption>Figure 4: Linearity Assumption Satisfied: Residuals vs.&nbsp;Fitted Plot shows no strong curvature of patterns</figcaption>
</figure>
</div>
</section>
<section id="b.-testing-for-independence" class="level4">
<h4 class="anchored" data-anchor-id="b.-testing-for-independence">4b. Testing for Independence</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The independence assumption stipulates that the residuals are independent of each other. To test for independence, we used the Durbin-Watson statistic, which tests for autocorrelation in the residuals. The Durbin-Watson statistic ranges from 0 to 4. A value close to 2 suggests no autocorrelation. If the value is significantly less than 2, it indicates positive autocorrelation, while a value significantly greater than 2 indicates negative autocorrelation.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Our analysis yielded a Durbin-Watson statistic of 1.77. This value is somewhat close to 2, suggesting that while there is a tendency towards positive autocorrelation, it is not extreme. In practice, DW values close to 2 (within a range of about 1.5 to 2.5) are often considered acceptable <span class="citation" data-cites="durbinwatson">(<a href="#ref-durbinwatson" role="doc-biblioref">Datalab, 2021</a>)</span>.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Given that the Durbin-Watson statistic indicated some positive correlation, we conducted the Breusch-Godfrey test to confirm and assess the extent of autocorrelation. The test yielded a statistic of 0.948 and a p-value of 0.330. Since this p-value exceeds the conventional significance threshold of 0.05, we conclude that there is no statistically significant evidence of autocorrelation in the residuals. This suggests that the residuals are likely independent, supporting the assumption of independence.</p>
</section>
<section id="c.-testing-for-homoscedasticity" class="level4">
<h4 class="anchored" data-anchor-id="c.-testing-for-homoscedasticity">4c. Testing for Homoscedasticity</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The homoscedasticity assumption requires that residuals have constant variance across all levels of the independent variable. Although we noted a minor curvature in the linearity assumption, <a href="#figure-5">Figure 5</a> shows no pronounced pattern of variance around the horizontal line, indicating that the homoscedasticity assumption is generally met.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/homosced1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure 5: Homoscedasticity Assumption Satisfied: Residuals are generally well-dispersed around the horizontal line"><img src="images/homosced1.png" class="img-fluid figure-img" alt="Figure 5: Homoscedasticity Assumption Satisfied: Residuals are generally well-dispersed around the horizontal line"></a></p>
<figcaption>Figure 5: Homoscedasticity Assumption Satisfied: Residuals are generally well-dispersed around the horizontal line</figcaption>
</figure>
</div>
</section>
<section id="d.-testing-for-normality" class="level4">
<h4 class="anchored" data-anchor-id="d.-testing-for-normality">4d. Testing for Normality</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The normality assumption requires that the residuals are normally distributed. To assess this, we created a Q-Q plot of the residuals, seen in <a href="#figure-6">Figure 6</a>. The points on the Q-Q plot slightly deviate but generally follow the 45-degree line, indicating that the residuals are approximately normally distributed.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/normality2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure 6: Normality Assumption Satisfied: Residuals generally align with the 45-degree reference line"><img src="images/normality2.png" class="img-fluid figure-img" alt="Figure 6: Normality Assumption Satisfied: Residuals generally align with the 45-degree reference line"></a></p>
<figcaption>Figure 6: Normality Assumption Satisfied: Residuals generally align with the 45-degree reference line</figcaption>
</figure>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We also performed the Shapiro-Wilk test for normality and got a test statistics of 0.99 and a p-value of 0.86 which suggest that the residuals are approximately normally distributed <span class="citation" data-cites="shapiro">(<a href="#ref-shapiro" role="doc-biblioref">Statistics, 2018</a>)</span>. Since the p-value is well above the conventional significance level of 0.05, there is no significant evidence to reject the null hypothesis of normality. This supports the assumption that the residuals follow a normal distribution.</p>
</section>
<section id="e.-testing-for-multicollinearity" class="level4">
<h4 class="anchored" data-anchor-id="e.-testing-for-multicollinearity">4e. Testing for Multicollinearity</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Multicollinearity occurs when independent variables are highly correlated, which can distort the estimation of regression coefficients <span class="citation" data-cites="multicollinearity">(<a href="#ref-multicollinearity" role="doc-biblioref">Data Science, 2018</a>)</span>. We evaluated multicollinearity using the Variance Inflation Factor (VIF) from the statsmodel library.</p>
<table class="table-striped table-hover table">
<caption>Table 6: Variance Inflations Factors for half of the selected features exceed 10, signaling high multicollinearity</caption>
<thead>
<tr class="header">
<th>Feature</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>debt_at_grad</code></td>
<td>26.534943</td>
</tr>
<tr class="even">
<td><code>avg_start_salary</code></td>
<td>21.435287</td>
</tr>
<tr class="odd">
<td><code>avg_debt_to_income</code></td>
<td>28.121863</td>
</tr>
<tr class="even">
<td><code>percent_mortgage</code></td>
<td>1.411813</td>
</tr>
<tr class="odd">
<td><code>percent_education_loan</code></td>
<td>7.590111</td>
</tr>
<tr class="even">
<td><code>generation_order</code></td>
<td>7.403381</td>
</tr>
</tbody>
</table>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Half of our features had a VIF value exceeding 10, signaling a significant concern <span class="citation" data-cites="VIF">(<a href="#ref-VIF" role="doc-biblioref">University, 2018a</a>)</span>. To further test this, we analyzed the condition number, which resulted in 241,000. There isn’t a simple definition of what counts as a small and large condition number, however, a condition value larger than 1,000 generally indicates strong multicollinearity <span class="citation" data-cites="conditionnumber">(<a href="#ref-conditionnumber" role="doc-biblioref">Chen, 2024</a>)</span>.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As we can see in <a href="#figure-7">Figure 7</a>, the correlation matrix reveals that <code>percent_mortgage</code> exhibits a moderate negative correlation of approximately -0.50 with the other variables. In contrast, the correlations among the remaining variables are notably higher, with values of 0.88 or above. This pattern suggests that while <code>percent_mortgage</code> is somewhat inversely related to the other variables, the high correlations among the latter indicate substantial multicollinearity within the dataset.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/correlationmatrix.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure 7: Correlation Matrix of Explanatory Variables: Displays strong pairwise correlations"><img src="images/correlationmatrix.png" class="img-fluid figure-img" alt="Figure 7: Correlation Matrix of Explanatory Variables: Displays strong pairwise correlations"></a></p>
<figcaption>Figure 7: Correlation Matrix of Explanatory Variables: Displays strong pairwise correlations</figcaption>
</figure>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This high multicollinearity is a common issue in survey-based observational studies, where variables are often interrelated due to underlying socio-economic factors <span class="citation" data-cites="observational">(<a href="#ref-observational" role="doc-biblioref">University, 2018b</a>)</span>. Such interdependencies reflect the inherent complexity of real-world data, where variables may be influenced by common factors or may capture overlapping aspects of the phenomena being studied. Despite efforts to mitigate multicollinearity by experimenting with different subsets of variables and dropping some from the analysis, these adjustments did not substantially reduce the multicollinearity problem. This persistent issue suggests that the high degree of correlation among the variables is an inherent characteristic of the data, making it difficult to isolate and interpret the individual effects of each variable.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Consequently, disentangling the unique contributions of each variable becomes challenging, as their high correlations obscure the individual effects and complicate the interpretation of their relationships. This issue can compromise the reliability and interpretability of our linear regression model by leading to unstable coefficient estimates and inflated standard errors. Although the other assumptions of the model are satisfied, the presence of multicollinearity necessitates cautious interpretation of our results.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Additionally, to ensure the validity of our model, we measure the following values:</p>
<ul>
<li>R-squared</li>
<li>Adjusted R-squared</li>
<li>Mean Absolute Error (MAE)</li>
<li>Mean Squared Error (MSE)</li>
<li>Root Mean Squared Error (RMSE)</li>
<li>F-statistic</li>
</ul>
</section>
</section>
<section id="building-a-random-forest-model" class="level3">
<h3 class="anchored" data-anchor-id="building-a-random-forest-model">5. Building a Random Forest Model</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Given the limitations identified in the linear regression model, we opted to perform a Random Forest analysis to further investigate the relationship between homeownership rates and various predictor variables. The primary motivation for this choice was to address some of the challenges and assumptions inherent in linear regression that may impact the robustness and interpretability of the results. Random Forest models, being ensemble methods based on decision trees, are less sensitive to multicollinearity and do not require the assumptions of linearity, homoscedasticity, or normality of residuals. This makes them a more flexible and robust alternative when dealing with correlated predictors. Overall, the Random Forest model provides an opportunity to validate and complement the findings from our linear regression analysis, offering a more comprehensive approach to analyzing the predictors of homeownership rates and mitigating some of the limitations observed in the linear model.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We utilized Scikit-learn’s RandomForest library to train and test the dataset on a 70%/30% split. Additionally, we plotted the features to determine the importance of the various features.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To ensure the validity of our model and compare the fit with our linear regression model, we measure the following values:</p>
<ul>
<li>R-squared</li>
<li>Adjusted R-squared</li>
<li>Mean Absolute Error (MAE)</li>
<li>Mean Squared Error (MSE)</li>
<li>Root Mean Squared Error (RMSE)</li>
</ul>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="trends-over-time" class="level2">
<h2 class="anchored" data-anchor-id="trends-over-time">Trends Over Time</h2>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Our analysis of graduation debt reveals a clear upward trajectory in average graduation debt levels over time for each successive generation, as shown in <a href="#figure-8">Figure 8</a>. For the Baby Boomers, graduates had relatively low levels of student loan debt, which remained stable and below $5,000 through the 1970s and early 1980s. In contrast, Generation X experienced a noticeable increase in debt levels starting in the late 1980s, with a steady rise through the 1990s, peaking around $15,000 by the early 2000s. This trend continues with Millennials, who faced the highest levels of debt at graduation. Starting in the early 2000s, the average debt for this generation saw a steep increase, surpassing $20,000 and reaching nearly $30,000 by 2015. This escalation in average student loan debt across generations highlights a growing financial burden on recent graduates, with Millennials bearing the highest debt load. The data suggest significant changes in higher education financing, economic conditions, and possibly policy impacts over the decades.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/debt_over_time.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure 8: Millennials faced the highest levels of debt at graduation compared to Baby Boomers and Generation X."><img src="images/debt_over_time.png" class="img-fluid figure-img" alt="Figure 8: Millennials faced the highest levels of debt at graduation compared to Baby Boomers and Generation X."></a></p>
<figcaption>Figure 8: Millennials faced the highest levels of debt at graduation compared to Baby Boomers and Generation X.</figcaption>
</figure>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The plot in <a href="#figure-9">Figure 9</a> illustrates homeownership rates from 1989 to 2022. The initial rate starts at around 47.5% and experiences a slight dip shortly after. From the early 1990s, there is a significant upward trend, peaking at around 62.5% by the mid-2000s. This peak occurred during a significant decade for mortgage rates, particularly influenced by the 2008 financial crisis <span class="citation" data-cites="mortgagerates2022">(<a href="#ref-mortgagerates2022" role="doc-biblioref">Campisi, 2022</a>)</span>. After reaching its peak, there is a noticeable decline starting in the late 2000s, likely influenced by the housing market crash and the global financial crisis around 2007-2008. From the mid-2010s onwards, there is a noticeable upward trend, with the homeownership rate climbing steadily to approximately 65% by 2022. This recent increase might be due to various factors, including economic recovery and an increase in housing demand.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/homeownership_over_time.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure 9: Fluctuations in Homeownership Rates from 1989 to 2022: Homeownership rate has increased steadily since 1989, with a decline in the late 2000s, and an upward trend from the mid-2010s onwards"><img src="images/homeownership_over_time.png" class="img-fluid figure-img" alt="Figure 9: Fluctuations in Homeownership Rates from 1989 to 2022: Homeownership rate has increased steadily since 1989, with a decline in the late 2000s, and an upward trend from the mid-2010s onwards"></a></p>
<figcaption>Figure 9: Fluctuations in Homeownership Rates from 1989 to 2022: Homeownership rate has increased steadily since 1989, with a decline in the late 2000s, and an upward trend from the mid-2010s onwards</figcaption>
</figure>
</div>
</section>
<section id="linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-model">Linear Regression Model</h2>
<section id="model-fit" class="level3">
<h3 class="anchored" data-anchor-id="model-fit">Model Fit</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To evaluate the effectiveness of the linear regression model in predicting the target variable, we examined several key performance metrics. These metrics provide insight into the model’s accuracy, fit, and overall statistical significance.</p>
<section id="model-test-statistics" class="level5">
<h5 class="anchored" data-anchor-id="model-test-statistics">Model test statistics:</h5>
<table class="table-striped table-hover table">
<caption>Table 7: Linear Regression model demonstrates a relatively good fit</caption>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R-squared</td>
<td>0.712</td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0.681</td>
</tr>
<tr class="odd">
<td>Mean Absolute Error (MAE)</td>
<td>10.5018</td>
</tr>
<tr class="even">
<td>Mean Squared Error (MSE)</td>
<td>130.3077</td>
</tr>
<tr class="odd">
<td>Root Mean Squared Error (RMSE)</td>
<td>11.4152</td>
</tr>
<tr class="even">
<td>F-statistic</td>
<td>23.43</td>
</tr>
<tr class="odd">
<td>P-value (F-statistic)</td>
<td>9.63e-14</td>
</tr>
</tbody>
</table>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The metrics displayed in Table 3 indicate the performance of the linear regression model. It demonstrates a relatively good fit, with an R-squared value of 0.712, indicating that 71.2% of the variability in homeownership rates is explained by the predictors. The Adjusted R-squared of 0.681 accounts for the number of predictors and indicates that the model remains robust even when adjusted for predictor complexity.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Mean Absolute Error (MAE) of 10.5018 represents the average magnitude of prediction errors, providing a straightforward measure of prediction accuracy. The Mean Squared Error (MSE) of 130.3077 and Root Mean Squared Error (RMSE) of 11.4152 further quantify the error magnitude, with RMSE being particularly useful for understanding error in the units of the target variable. Additionally, the F-statistic of 23.43, with a p-value of 9.63e-14, indicates that the overall model is statistically significant, meaning the predictors collectively contribute meaningfully to explaining the variability in the target variable.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;These metrics collectively demonstrate that the linear regression model has a good fit and effectively captures the relationship between the predictors and the target variable, though there may still be room for improvement in model performance by addressing multicollinearity.</p>
</section>
<section id="coefficient-results" class="level5">
<h5 class="anchored" data-anchor-id="coefficient-results">Coefficient Results</h5>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To understand the influence of each feature on homeownership rate, we examined the coefficients and corresponding p-values of the linear regression model. The coefficients indicate the strength and direction of the relationship between each feature and homeownership rate, while the p-values assess the statistical significance of these relationships.</p>
<table class="table-striped table-hover table">
<caption>Table 8: Linear regression coefficients ranked from least to most statistically significant</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 45%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Coefficient</th>
<th>P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>generation_order</code></td>
<td>-5.4525</td>
<td>0.317</td>
</tr>
<tr class="even">
<td><code>avg_debt_to_income</code></td>
<td>-0.7455</td>
<td>0.124</td>
</tr>
<tr class="odd">
<td><code>debt_at_grad</code></td>
<td>0.0016</td>
<td>0.063</td>
</tr>
<tr class="even">
<td><code>percent_education_loan</code></td>
<td>0.7697</td>
<td>0.054</td>
</tr>
<tr class="odd">
<td><code>avg_start_salary</code></td>
<td>-0.0013</td>
<td>0.025</td>
</tr>
<tr class="even">
<td><code>percent_mortgage</code></td>
<td>0.6844</td>
<td>0.000</td>
</tr>
</tbody>
</table>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We anticipated that <code>debt_at_grad</code>, <code>percent_education_loan</code>, and <code>generation_order</code> would be the most influential features. However, the observed relationships were not as straightforward as expected.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The coefficient for <code>debt_at_grad</code> indicates a modest positive relationship with homeownership rate, suggesting that increased graduation debt is associated with higher homeownership rates. However, the p-value for this coefficient exceeds conventional significance levels, casting uncertainty on its precise impact. Similarly, the coefficient for <code>percent_education_loan</code> indicates an unexpected positive association between education loan debt and homeownership rates. This counterintuitive result may be due to several factors, including high multicollinearity, sampling issues, or specific economic conditions influencing the observed relationship. For instance, it may suggest that individuals with higher education debt, despite the financial burden, could achieve higher earning potential, enabling them to afford homeownership.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In contrast, the coefficient for <code>generation_order</code> exhibits a negative relationship, indicating that the generational cohort to which an individual belongs may be inversely related to homeownership rates. Despite being the largest negative coefficient, the lack of statistical significance suggests that this effect is not robust within the framework of this model. This result could be influenced by various factors, including high multicollinearity among the features included in the regression model.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The coefficient analysis reveals that <code>percent_mortgage</code> exhibits the highest positive and statistically significant effect, with a coefficient of 0.6844 and a p-value of 0. This finding aligns with practical expectations, as mortgage debt is a critical determinant of homeownership. The variables <code>avg_start_salary</code> and <code>avg_debt_to_income</code> were included to refine the model. Notably, <code>avg_start_salary</code> has a slight negative association with homeownership rates, suggesting that higher starting salaries might correlate with lower homeownership, though this effect is minor. Additionally, while <code>avg_debt_to_income</code> shows a negative trend, its p-value indicates that this relationship is not statistically significant at the 0.05 level, suggesting potential weakness or confounding factors.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Overall, the coefficients offer a nuanced view of how differences in student loan debt between older and current generations affect homeownership trends but do not provide a definitive answer. To achieve a more definitive understanding of the impact of student loan debt on homeownership trends, several methodological improvements could be employed. Longitudinal studies, which track individuals over time, would allow for a clearer examination of how changes in student loan debt influence homeownership. Additionally, addressing multicollinearity through variable selection or principal component analysis, enhancing data quality, and incorporating larger, more diverse samples would strengthen the reliability of findings.</p>
</section>
</section>
</section>
<section id="random-forest-model" class="level2">
<h2 class="anchored" data-anchor-id="random-forest-model">Random Forest Model</h2>
<section id="model-fit-1" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-1">Model Fit</h3>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In this model analysis, we utilized the same dependent and independent variables as our linear regression model and a similar 70% training and 30% testing split.</p>
<section id="model-test-statistics-1" class="level5">
<h5 class="anchored" data-anchor-id="model-test-statistics-1">Model test statistics:</h5>
<table class="table-striped table-hover table">
<caption>Table 9: Random Forest model demonstrates a better fit than linear regression model</caption>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean Squared Error (MSE)</td>
<td>75.7782</td>
</tr>
<tr class="even">
<td>R-squared</td>
<td>0.7452</td>
</tr>
<tr class="odd">
<td>Adjusted R-squared</td>
<td>0.6724</td>
</tr>
<tr class="even">
<td>Mean Absolute Error (MAE)</td>
<td>6.5159</td>
</tr>
<tr class="odd">
<td>Root Mean Squared Error (RMSE)</td>
<td>8.7051</td>
</tr>
</tbody>
</table>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;he Mean Squared Error was 75.78, far better than our linear regression MSE score of 130.30. Although an MSE of 75.78 suggests some level of error in the predictions, it is a useful benchmark for comparing the model’s performance with our linear regression model. The R-squared value was 0.745, which signifies that approximately 74.5% of the variability in homeownership rates can be explained by the model. The Adjusted R-squared is slightly lower than the R-squared, reflecting the adjustment for the number of predictors. This suggests that while the model is still strong, the inclusion of additional variables has not significantly improved the model’s explanatory power. Overall, the Random Forest model outperforms the linear regression model in terms of R-squared, MAE, MSE, and RMSE, indicating better prediction accuracy and fit to the data.</p>
</section>
<section id="feature-importance-results" class="level5">
<h5 class="anchored" data-anchor-id="feature-importance-results">Feature Importance Results</h5>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To better understand the factors influencing homeownership rates, we analyzed the importance of various features using a Random Forest model. The feature importance table below provides a quantitative measure of how much each feature contributes to the prediction of homeownership rates.</p>
<table class="table-striped table-hover table">
<caption>Table 10: debt_at_grad and percent_education_loan rank as the top two most important features, after percent_mortgage</caption>
<thead>
<tr class="header">
<th>Feature</th>
<th>Importance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>generation_order</code></td>
<td>0.03846002578869567</td>
</tr>
<tr class="even">
<td><code>avg_start_salary</code></td>
<td>0.0726717567809253</td>
</tr>
<tr class="odd">
<td><code>avg_debt_to_income</code></td>
<td>0.08913656748564287</td>
</tr>
<tr class="even">
<td><code>debt_at_grad</code></td>
<td>0.09359463522665826</td>
</tr>
<tr class="odd">
<td><code>percent_education_loan</code></td>
<td>0.11617657198613383</td>
</tr>
<tr class="even">
<td><code>percent_mortgage</code></td>
<td>0.5899604427319441</td>
</tr>
</tbody>
</table>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To aid in visualizing the importance of different features, we created a plot of their respective importances. We excluded <code>percent_mortgage</code> from this visualization due to its dominance as the most significant feature.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As illustrated in <a href="#figure-10">Figure 10</a>, the variables <code>percent_education_loan</code> and <code>debt_at_grad</code> emerge as the top most influential factors in predicting the homeownership rate. The importance of <code>percent_education_loan</code> (0.1162) and <code>debt_at_grad</code> (0.0936) indicates that the amount of student loan debt significantly affects an individual’s likelihood of owning a home. This finding suggests that high levels of student loan debt can be a substantial barrier to homeownership, likely due to the financial strain it imposes on individuals, thereby limiting their ability to save for or afford a home.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In contrast, <code>generation_order</code> has the lowest importance score (0.0385) among the features analyzed. This result implies that the generational cohort of an individual—such as Baby Boomer, Gen X, or Millennials—has minimal influence on predicting homeownership rates in comparison to more direct financial factors. The features <code>average_start_salary</code> (0.0727) and <code>avg_debt_to_income</code> (0.0891) also contribute to the model, though their impact is less pronounced than that of student loan-related variables. This suggests that while starting salary and debt-to-income ratios are relevant factors in homeownership decisions, they are not as significant as the financial burden imposed by student loans.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/features.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure 10: Generational cohort is the least significant predictor of homeownership rate."><img src="images/features.png" class="img-fluid figure-img" alt="Figure 10: Generational cohort is the least significant predictor of homeownership rate."></a></p>
<figcaption>Figure 10: Generational cohort is the least significant predictor of homeownership rate.</figcaption>
</figure>
</div>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Overall, the feature importance analysis underscores the dominant role of student loan debt in influencing homeownership likelihood. The results highlight that financial factors, particularly those related to student loans and debt, are critical in understanding and predicting homeownership trends.</p>
</section>
</section>
</section>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In addressing our research question—how do differences in student loan debt between older and current generations affect homeownership trends?—our study offers both insightful and nuanced perspectives. The historical context and the analysis reveal a complex relationship between student loan debt and homeownership rates. Our findings indicate that student loan debt at graduation is a significant factor influencing homeownership rates. The data show a clear increase in student loan debt across generations, with Millennials bearing the highest levels, which is likely contributing to the challenges they face in achieving homeownership.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Our analysis revealed a marked increase in average graduation debt from Baby Boomers to Millennials, with Millennials bearing the highest levels of debt. This rise in debt aligns with a trend of increasing financial burden on recent graduates. Our examination of homeownership rates indicated significant fluctuations influenced by economic events, such as the 2008 financial crisis, yet an overall upward trend in recent years.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Linear Regression model provided a good fit with an R-squared value of 0.712 and significant predictors such as mortgage debt, though the results were tempered by issues such as multicollinearity and the limitations of aggregated data. The Random Forest model outperformed the linear regression model in predictive accuracy, with an R-squared value of 0.745 and demonstrated that student loan-related variables, particularly <code>debt_at_grad</code> and <code>percent_education_loan</code>, were the most influential factors affecting homeownership rates.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;While the Random Forest model provided more robust results, the linear regression model’s findings were also valuable, highlighting the complexity of the relationships between debt and homeownership. The models collectively suggest that high levels of student loan debt are a barrier to homeownership, though challenges like multicollinearity and data limitations need to be addressed. The confidence in our results is bolstered by the consistency between the two modeling approaches, despite the inherent limitations of the data.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Through our linear regression and Random Forest analyses, we confirmed that <code>debt_at_grad</code> has a less pronounced but still notable effect. <code>Percent_education_loan</code>, while less influential than mortgage debt, also plays a role, suggesting that education loan debt does impact homeownership trends to a degree. Interestingly, <code>generation_order</code>, representing the sequence of generations, was found to be the least significant predictor of homeownership rates. While generational trends and experiences might shape broader economic and social patterns, the specific generational cohort an individual belongs to does not substantially explain variations in homeownership rates compared to the financial burden of student loans and mortgages.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As illustrated in <a href="#figure-10">Figure 10</a>, the variables <code>percent_education_loan</code> and <code>debt_at_grad</code> emerge as the most influential factors in predicting the homeownership rate. This highlights the significant role that student loan debt plays in determining an individual’s likelihood of owning a home. The substantial impact of <code>percent_education_loan</code> suggests that the proportion of education-related debt an individual carries is a determinant of homeownership. Similarly, <code>debt_at_grad</code> indicates that the amount of debt incurred by graduation also affects homeownership prospects.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It is crucial to acknowledge that student loan debt is not the sole determinant of homeownership trends. Inflation, for instance, has affected purchasing power and contributed to rising housing costs, which can make homeownership more challenging for many. Additionally, extensive evidence highlights how student loan debt creates barriers in mortgage eligibility and credit scores. According to a study by the Federal Reserve Board, a $1,000 increase in student loan debt is associated with a 1.8 percent decrease in the homeownership rate for public four-year college graduates, resulting in a delay in purchasing a home <span class="citation" data-cites="ChicagoJournal">(<a href="#ref-ChicagoJournal" role="doc-biblioref">Mezza et al., 2020</a>)</span>. Furthermore, as addressed above, despite our efforts to mitigate bias, the potential for underrepresentation of certain demographics in the survey samples remains a concern. Student loan debt can exacerbate racial disparities. Racial wealth and income gaps are rooted in historical discriminatory housing policies, meaning that Black students, in particular, may face greater financial risks in pursuing higher education <span class="citation" data-cites="race">(<a href="#ref-race" role="doc-biblioref">Fallon, 2022</a>)</span>. Not adequately capturing the experiences of these underrepresented groups can affect our research and must be taken into consideration when evaluating our results.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In summary, while student loan debt does impact homeownership trends, it is just one of several factors contributing to the complexity of financial decisions related to homeownership. The rising debt levels faced by Millennials and Gen Z are significant but must be considered alongside other financial elements such as debt levels, income, and savings. Our research underscores the need for a holistic view when analyzing homeownership trends and suggests that addressing the broader financial challenges faced by younger generations may be crucial in facilitating increased homeownership rates. This insight also emphasizes the need for targeted policies and interventions that address financial barriers directly, rather than focusing solely on generational characteristics. By prioritizing measures that alleviate student loan debt and improve financial stability, stakeholders can more effectively support homeownership aspirations across different generational cohorts.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-homeownership2024" class="csl-entry" role="listitem">
Association, N. B. M. (2024). <em>Homeownership Month with City National Bank</em>. <a href="https://www.labmba.org/blog/homeownership-month-with-city-national-bank">https://www.labmba.org/blog/homeownership-month-with-city-national-bank</a>
</div>
<div id="ref-generations" class="csl-entry" role="listitem">
Bialik, K., &amp; Fry, R. (2019). <em>Millennial Life: How Young Adulthood Today Compares with Prior Generations</em>. <a href="https://www.pewresearch.org/social-trends/2019/02/14/millennial-life-how-young-adulthood-today-compares-with-prior-generations-2/">https://www.pewresearch.org/social-trends/2019/02/14/millennial-life-how-young-adulthood-today-compares-with-prior-generations-2/</a>
</div>
<div id="ref-Census2019" class="csl-entry" role="listitem">
Bureau, U. S. C. (2024). <em>Housing Vacancies and Homeownership (CPS/HVS)</em>. <a href="https://www.census.gov/housing/hvs/data/histtabs.html">https://www.census.gov/housing/hvs/data/histtabs.html</a>
</div>
<div id="ref-mortgagerates2022" class="csl-entry" role="listitem">
Campisi, N. (2022). <em>Mortgage Rates History</em>. <a href="https://www.forbes.com/advisor/mortgages/mortgage-rates-history/">https://www.forbes.com/advisor/mortgages/mortgage-rates-history/</a>
</div>
<div id="ref-conditionnumber" class="csl-entry" role="listitem">
Chen, G. (2024). <em>Multicollinearity (and Model Validation</em>. <a href="https://www.sjsu.edu/faculty/guangliang.chen/Math261a/Ch9slides-multicollinearity.pdf">https://www.sjsu.edu/faculty/guangliang.chen/Math261a/Ch9slides-multicollinearity.pdf</a>
</div>
<div id="ref-FederalReserveBoston" class="csl-entry" role="listitem">
Cooper, D. H., &amp; Wang, J. C. (2014). <em>Student Loan Debt and Economic Outcomes</em>. <a href="https://www.bostonfed.org/publications/current-policy-perspectives/2014/student-loan-debt-and-economic-outcomes.aspx">https://www.bostonfed.org/publications/current-policy-perspectives/2014/student-loan-debt-and-economic-outcomes.aspx</a>
</div>
<div id="ref-multicollinearity" class="csl-entry" role="listitem">
Data Science, P. for. (2018). <em>Linear Regression</em>. <a href="https://www.pythonfordatascience.org/linear-regression-python/">https://www.pythonfordatascience.org/linear-regression-python/</a>
</div>
<div id="ref-durbinwatson" class="csl-entry" role="listitem">
Datalab, A. (2021). <em>Understanding Durbin-Watson Test</em>. <a href="https://medium.com/@analyttica/durbin-watson-test-fde429f79203">https://medium.com/@analyttica/durbin-watson-test-fde429f79203</a>
</div>
<div id="ref-CFR" class="csl-entry" role="listitem">
Editors, CFR. org. (2024). <em>Is Rising Student Debt Harming the u.s. Economy?</em> <a href="https://www.cfr.org/backgrounder/us-student-loan-debt-trends-economic-impact">https://www.cfr.org/backgrounder/us-student-loan-debt-trends-economic-impact</a>
</div>
<div id="ref-race" class="csl-entry" role="listitem">
Fallon, K. (2022). <em>How Student Loan Debt Affects the Racial Homeownership Gap</em>. <a href="https://housingmatters.urban.org/articles/how-student-loan-debt-affects-racial-homeownership-gap">https://housingmatters.urban.org/articles/how-student-loan-debt-affects-racial-homeownership-gap</a>
</div>
<div id="ref-Upjohn" class="csl-entry" role="listitem">
Gicheva, D., &amp; Thompson, J. (2015). <em>The Effects of Student Loans on Long-Term Household Financial Stability</em>. <a href="https://research.upjohn.org/cgi/viewcontent.cgi?filename=8&amp;article=1249&amp;context=up_press&amp;type=additional">https://research.upjohn.org/cgi/viewcontent.cgi?filename=8&amp;article=1249&amp;context=up_press&amp;type=additional</a>
</div>
<div id="ref-federal2024" class="csl-entry" role="listitem">
Governors of the Federal Reserve System, B. of. (2020). <em>Consumer Credit Outstanding</em>. <a href="https://www.federalreserve.gov/releases/g19/HIST/cc_hist_memo_levels.html">https://www.federalreserve.gov/releases/g19/HIST/cc_hist_memo_levels.html</a>
</div>
<div id="ref-equitablegrowth" class="csl-entry" role="listitem">
Kopparam, R., &amp; Clemens, A. (2020). <em>The Rising Number of u.s. Households with Burdensome Student Debt Calls for a Federal Response</em>. <a href="https://equitablegrowth.org/the-rising-number-of-u-s-households-with-burdensome-student-debt-calls-for-a-federal-response/">https://equitablegrowth.org/the-rising-number-of-u-s-households-with-burdensome-student-debt-calls-for-a-federal-response/</a>
</div>
<div id="ref-NIH" class="csl-entry" role="listitem">
Martin, E. C., &amp; E., Dwyer. R. (2021). <em>Financial Stress, Race, and Student Debt During the Great Recession</em>. <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10373449/">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10373449/</a>
</div>
<div id="ref-Studentdebt2023" class="csl-entry" role="listitem">
McLoughlin, D. (2023). <em>Student Loan Debt Statistics by Year</em>. <a href="https://wordsrated.com/student-loan-debt-by-year/">https://wordsrated.com/student-loan-debt-by-year/</a>
</div>
<div id="ref-ChicagoJournal" class="csl-entry" role="listitem">
Mezza, A., Ringo, D., Sherlund, S., &amp; Sommer, K. (2020). Student Loans and Homeownership. <em>Journal of Labor Economics</em>, <em>38</em>(1).
</div>
<div id="ref-shapiro" class="csl-entry" role="listitem">
Statistics, L. (2018). <em>Testing for Normality Using SPSS Statistics</em>. <a href="https://statistics.laerd.com/spss-tutorials/testing-for-normality-using-spss-statistics.php#:~:text=If%20the%20Sig.,deviate%20from%20a%20normal%20distribution">https://statistics.laerd.com/spss-tutorials/testing-for-normality-using-spss-statistics.php#:~:text=If%20the%20Sig.,deviate%20from%20a%20normal%20distribution</a>
</div>
<div id="ref-VIF" class="csl-entry" role="listitem">
University, T. P. S. (2018a). <em>Detecting Multicollinearity Using Variance Inflation Factors</em>. <a href="https://online.stat.psu.edu/stat462/node/180/#:~:text=The%20general%20rule%20of%20thumb,of%20serious%20multicollinearity%20requiring%20correction">https://online.stat.psu.edu/stat462/node/180/#:~:text=The%20general%20rule%20of%20thumb,of%20serious%20multicollinearity%20requiring%20correction</a>
</div>
<div id="ref-observational" class="csl-entry" role="listitem">
University, T. P. S. (2018b). <em>What Is Multicollinearity?</em> <a href="https://online.stat.psu.edu/stat501/lesson/12/12.1">https://online.stat.psu.edu/stat501/lesson/12/12.1</a>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","selector":".lightbox","openEffect":"zoom","loop":false,"descPosition":"bottom"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>